# Configuração do banco H2
spring.datasource.url=jdbc:h2:mem:gasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra o SQL no console para você debugar o que o Hibernate está fazendo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# O Hibernate vai criar as tabelas automaticamente com base nas nossas classes
spring.jpa.hibernate.ddl-auto=update

# Habilita a interface visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

evolution.api.base-url=http://localhost:8080
evolution.api.instance=default
evolution.api.key=
app.pix.key=CHAVE_PIX_AQUI